project_name: my-cpp-service
language: cpp
build_tool: make
deployment: terraform
environment: dev
branching:
  type: env-based  # or semantic-versioning
  rules:
    - dev
    - staging
    - main

stages:
  - lint
  - static_analysis
  - unit_test
  - build
  - deploy